### ISSUE TITLE
Suggestion: Drop the 1 block cable and go "redstone (a)like"

### ISSUE THREAD

**Issue by ShelLuser** [Tamaized/Dal-Quor#115]
Disclaimer: I can well understand if this gets rejected, but that never stopped me from suggesting :)

I _really_ like this mod, the whole idea alone of exploring the Void itself intrigues me (it helps if you're a vivid and enthusiastic Minecraft player).

Here's my concern: cables are common. A generator, cables, maybe batteries. Seen that, done it....

Why not go back to basics? Sure, it will limit us players but I'm sure I can come up with reasoning (lemme think)..  But I think you might want to consider to set yourself even more apart by utilizing redstone mechanics, so no more cables but a conduit which needs to be placed down (like redstone dust) in order to make it work. Yes I realize all too well: an infusion altar on top of a power generator is going to be tricky if not impossible. Who ever said wielding void energy was easy in the first place? Considering the obsticles of even visiting the Void I think it would add up to not making this too easy.

"Voidic power is used to empower the voidic machines. Its essense is so powerful that it cannot be harnassed by anything known to man and therefor needs to be placed down on the ground. By doing so it will cut down into the very essence of the material and render it useless".

My idea is a black (vs red) speck trail on the blocks which represents the dark energies.

Ok, so another added suggestion: if possible render any associated block void (pun intended).

If placed on a block it should render that block useless. So if the void or the underlying block gets removed both get removed and that'll be the end of it. I know I'm repeating myself: who said trying to wield void energy should be easy? ;)

Just my 2 cents of course.

**Comment by Tamaized** [comment]
A neat concept, I'll keep it in mind. Though the reason I decided for the look that it has now is it's supposed to closely resembles the Void Crystal Block which, I guess you can call this lore if you want to, is basically a conduit for the void itself.

**Comment by Tamaized** [comment]
Closing due to deprecation
