### ISSUE TITLE
Portal death negates grave

### ISSUE THREAD

**Issue by aleckohol** [Tamaized/Dal-Quor#187]
Had a problem with the voidcraft portals in a modpack where travelling from the void dimension to the overworld would cause a laggy loop and I'd be sent back and forth until I ultimately died from suffocating in a wall. The problem with this is both deaths were not in a wall and the deathpoint shows the exact tile of the portal itself and no grave is spawned.

**Comment by Tamaized** [comment]
What version of TamModized

**Comment by aleckohol** [comment]
VoidCraft-1.12-0.24.2

**Comment by Tamaized** [comment]
Quite odd, shouldn't be possible for the portal to resend you back and forth like that, I have checks to prevent that. The grave not spawning however, not sure on that one.

**Comment by aleckohol** [comment]
I just encountered another problem as well. Is it intended that you can die
by "falling out of the world" when flying up too high in The Void? Because
this just happened to me.

**Comment by Tamaized** [comment]
Intentional, you need a potion of plenum
