### ISSUE TITLE
(suggestion) merging of the 3 dimensions

### ISSUE THREAD

**Issue by Hypsellis** [Tamaized/Dal-Quor#219]
I wondered why the void dimension was separated in 3 different dimensions. It makes 2 empty dimensions except the temple, and use of more biome and dimension ids. I know they have each one a particular use, and make the progression slower. But I thought the Xia and Dal Quor temple could be at specific unique location in the void, the dimension center, as AbyssalCraft does the with the J'zahar temple inside the Omothol. The portals could be used to reach the places easily and quickly. I wanted to get your opinion about it.

**Comment by Tamaized** [comment]
The Void, Dal Quor, and Xia are 3 different dimensions lore wise, they're not located in the same plane. It's as simple as that. I have plans to expand on all 3. The mod is insanely under developed right now.

**Comment by Hypsellis** [comment]
Ok I can't wait to see it, you do really awesome work. :)
