### ISSUE TITLE
VoidCraft-1.10.2-0.19.6 - Xia palace issue

### ISSUE THREAD

**Issue by Cenbes** [Tamaized/Dal-Quor#224]
Hello, i tried this version of mod and i have trouble spawning Xia temple. Portal doesnt spawn at all, only foire in soft bedrock. I cant even find portal in JEI. And also there is none of those boses. Once i was able to find doorway to Xia room with osme binding blocks,, but nothing else.

**Comment by Tamaized** [comment]
The 1.10 version is both outdated and upsupported

**Comment by Cenbes** [comment]
ok so, just dleete in 1.10 version, bcs in syngle player it worked, but crashed at Avatar. So it is meybe so kind of sponge issue, try Server with sponge forge for 1.12 then pls.

https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2
