### ISSUE TITLE
Crash, seems to be an incompatibility between Voidcraft and Matter Overdrive

### ISSUE THREAD

**Issue by Buttcrackofthunder** [Tamaized/Dal-Quor#227]
I crashed out of the blue due to something thaumcraft related:
https://pastebin.com/7ZXKVtrQ
when I tried to reload, the game told me that it is loading a backup level.dat and to make a backup of the world, I said fine and it started loading. then it crashed with this error:
https://pastebin.com/gkwkpXbc
I'm not sure what this is, but it seems that voidcraft tried to do something to a block from MO and it didn't like that, so it crashed.
I don't know how to read the log, but can it give me the exact position of the errored block? I could delete it with MCedit

**Comment by SensualBardNoise** [comment]
Well the report states

-- Block being updated --
Details:
    Source block type: ID #2401 (tile.holo_sign // matteroverdrive.blocks.BlockHoloSign)
    Block: matteroverdrive:tritanium_crate_black[facing=south]
    Block location: World: (53,78,82), Chunk: (at 5,4,2 in 3,5; contains blocks 48,0,80 to 63,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

That's about what all information I can find regarding that.

What were you doing before thaumcraft crashed the game? Did anything trigger it you could tell? Did you do anything after the backup loaded? Or was it just a crash upon loading?

This information would be helpful to help figure out what caused it for Tamaized.

**Comment by Buttcrackofthunder** [comment]
I was out exploring and ran across a magical forest. I looked around a bit and it seems to be a known bug with Beta 15 (which I rolled back because it's buggy as hell)
My world was shot anyway, too many conficts and ID issues and my region file got corrupted, so I started a new one, I the old one was unsalvageable.
I'll reopen this one should it happen again, alright?

**Comment by Tamaized** [comment]
Note, I already know the cause but why their TE was in that spot when it shouldn't be is another issue but I guess a corrupt world answers that.
